const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
const SET_SIDEDRAWER_STATE = 'SET_SIDEDRAWER_STATE';
const SET_HEADER_BG = 'SET_HEADER_BG';

export {
    SET_SEARCH_VALUE, 
    SET_SIDEDRAWER_STATE,
    SET_HEADER_BG
}
