const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
const SET_SIDEDRAWER_STATE = 'SET_SIDEDRAWER_STATE';
const SET_HEADER_BG = 'SET_HEADER_BG';
const SET_MODAL_STATE = 'SET_MODAL_STATE';

const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

const GET_PRODUCT_DETAIL_START = 'GET_PRODUCT_DETAIL_START';
const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCTS_DETAIL_SUCCESS';
const GET_PRODUCT_DETAIL_FAIL = 'GET_PRODUCTS_FAIL';
const REST_PRODUCT_DETAIL = 'REST_PRODUCT_DETAIL';



export {
    SET_SEARCH_VALUE, 
    SET_SIDEDRAWER_STATE,
    SET_HEADER_BG,
    GET_PRODUCTS_START,
    GET_PRODUCTS_SUCCESS,
    GET_PRODUCTS_FAIL,
    GET_PRODUCT_DETAIL_START,
    GET_PRODUCT_DETAIL_SUCCESS,
    GET_PRODUCT_DETAIL_FAIL,
    REST_PRODUCT_DETAIL,
    SET_MODAL_STATE,
}
