const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
const SET_SIDEDRAWER_STATE = 'SET_SIDEDRAWER_STATE';
const SET_HEADER_BG = 'SET_HEADER_BG';

const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';


export {
    SET_SEARCH_VALUE, 
    SET_SIDEDRAWER_STATE,
    SET_HEADER_BG,
    GET_PRODUCTS_START,
    GET_PRODUCTS_SUCCESS,
    GET_PRODUCTS_FAIL,
}
